/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAlertsRouteImport } from './routes/_authenticated.alerts'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedCalibrationRouteImport } from './routes/_authenticated.calibration'
import { Route as AuthenticatedChemicalsRouteImport } from './routes/_authenticated.chemicals'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated.devices'
import { Route as AuthenticatedEquipmentRouteImport } from './routes/_authenticated.equipment'
import { Route as AuthenticatedGuidanceRouteImport } from './routes/_authenticated.guidance'
import { Route as AuthenticatedIncidentsRouteImport } from './routes/_authenticated.incidents'
import { Route as AuthenticatedIntegrationRouteImport } from './routes/_authenticated.integration'
import { Route as AuthenticatedLabsRouteImport } from './routes/_authenticated.labs'
import { Route as AuthenticatedMonitoringRouteImport } from './routes/_authenticated.monitoring'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedMonitoringLabIdRouteImport } from './routes/_authenticated.monitoring.$labId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAlertsRoute = AuthenticatedAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalibrationRoute =
  AuthenticatedCalibrationRouteImport.update({
    id: '/calibration',
    path: '/calibration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChemicalsRoute = AuthenticatedChemicalsRouteImport.update({
  id: '/chemicals',
  path: '/chemicals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipmentRoute = AuthenticatedEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuidanceRoute = AuthenticatedGuidanceRouteImport.update({
  id: '/guidance',
  path: '/guidance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIncidentsRoute = AuthenticatedIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationRoute =
  AuthenticatedIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabsRoute = AuthenticatedLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitoringRoute = AuthenticatedMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitoringLabIdRoute =
  AuthenticatedMonitoringLabIdRouteImport.update({
    id: '/$labId',
    path: '/$labId',
    getParentRoute: () => AuthenticatedMonitoringRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calibration': typeof AuthenticatedCalibrationRoute
  '/chemicals': typeof AuthenticatedChemicalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/guidance': typeof AuthenticatedGuidanceRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/labs': typeof AuthenticatedLabsRoute
  '/monitoring': typeof AuthenticatedMonitoringRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/monitoring/$labId': typeof AuthenticatedMonitoringLabIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alerts': typeof AuthenticatedAlertsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/calibration': typeof AuthenticatedCalibrationRoute
  '/chemicals': typeof AuthenticatedChemicalsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/equipment': typeof AuthenticatedEquipmentRoute
  '/guidance': typeof AuthenticatedGuidanceRoute
  '/incidents': typeof AuthenticatedIncidentsRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/labs': typeof AuthenticatedLabsRoute
  '/monitoring': typeof AuthenticatedMonitoringRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/monitoring/$labId': typeof AuthenticatedMonitoringLabIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/alerts': typeof AuthenticatedAlertsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/calibration': typeof AuthenticatedCalibrationRoute
  '/_authenticated/chemicals': typeof AuthenticatedChemicalsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/equipment': typeof AuthenticatedEquipmentRoute
  '/_authenticated/guidance': typeof AuthenticatedGuidanceRoute
  '/_authenticated/incidents': typeof AuthenticatedIncidentsRoute
  '/_authenticated/integration': typeof AuthenticatedIntegrationRoute
  '/_authenticated/labs': typeof AuthenticatedLabsRoute
  '/_authenticated/monitoring': typeof AuthenticatedMonitoringRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/monitoring/$labId': typeof AuthenticatedMonitoringLabIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/calibration'
    | '/chemicals'
    | '/dashboard'
    | '/devices'
    | '/equipment'
    | '/guidance'
    | '/incidents'
    | '/integration'
    | '/labs'
    | '/monitoring'
    | '/reports'
    | '/monitoring/$labId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alerts'
    | '/analytics'
    | '/calibration'
    | '/chemicals'
    | '/dashboard'
    | '/devices'
    | '/equipment'
    | '/guidance'
    | '/incidents'
    | '/integration'
    | '/labs'
    | '/monitoring'
    | '/reports'
    | '/monitoring/$labId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/alerts'
    | '/_authenticated/analytics'
    | '/_authenticated/calibration'
    | '/_authenticated/chemicals'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/equipment'
    | '/_authenticated/guidance'
    | '/_authenticated/incidents'
    | '/_authenticated/integration'
    | '/_authenticated/labs'
    | '/_authenticated/monitoring'
    | '/_authenticated/reports'
    | '/_authenticated/monitoring/$labId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/alerts': {
      id: '/_authenticated/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AuthenticatedAlertsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calibration': {
      id: '/_authenticated/calibration'
      path: '/calibration'
      fullPath: '/calibration'
      preLoaderRoute: typeof AuthenticatedCalibrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chemicals': {
      id: '/_authenticated/chemicals'
      path: '/chemicals'
      fullPath: '/chemicals'
      preLoaderRoute: typeof AuthenticatedChemicalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipment': {
      id: '/_authenticated/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthenticatedEquipmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guidance': {
      id: '/_authenticated/guidance'
      path: '/guidance'
      fullPath: '/guidance'
      preLoaderRoute: typeof AuthenticatedGuidanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/incidents': {
      id: '/_authenticated/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthenticatedIncidentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integration': {
      id: '/_authenticated/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AuthenticatedIntegrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/labs': {
      id: '/_authenticated/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof AuthenticatedLabsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring': {
      id: '/_authenticated/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthenticatedMonitoringRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring/$labId': {
      id: '/_authenticated/monitoring/$labId'
      path: '/$labId'
      fullPath: '/monitoring/$labId'
      preLoaderRoute: typeof AuthenticatedMonitoringLabIdRouteImport
      parentRoute: typeof AuthenticatedMonitoringRoute
    }
  }
}

interface AuthenticatedMonitoringRouteChildren {
  AuthenticatedMonitoringLabIdRoute: typeof AuthenticatedMonitoringLabIdRoute
}

const AuthenticatedMonitoringRouteChildren: AuthenticatedMonitoringRouteChildren =
  {
    AuthenticatedMonitoringLabIdRoute: AuthenticatedMonitoringLabIdRoute,
  }

const AuthenticatedMonitoringRouteWithChildren =
  AuthenticatedMonitoringRoute._addFileChildren(
    AuthenticatedMonitoringRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAlertsRoute: typeof AuthenticatedAlertsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedCalibrationRoute: typeof AuthenticatedCalibrationRoute
  AuthenticatedChemicalsRoute: typeof AuthenticatedChemicalsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedEquipmentRoute: typeof AuthenticatedEquipmentRoute
  AuthenticatedGuidanceRoute: typeof AuthenticatedGuidanceRoute
  AuthenticatedIncidentsRoute: typeof AuthenticatedIncidentsRoute
  AuthenticatedIntegrationRoute: typeof AuthenticatedIntegrationRoute
  AuthenticatedLabsRoute: typeof AuthenticatedLabsRoute
  AuthenticatedMonitoringRoute: typeof AuthenticatedMonitoringRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertsRoute: AuthenticatedAlertsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedCalibrationRoute: AuthenticatedCalibrationRoute,
  AuthenticatedChemicalsRoute: AuthenticatedChemicalsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedEquipmentRoute: AuthenticatedEquipmentRoute,
  AuthenticatedGuidanceRoute: AuthenticatedGuidanceRoute,
  AuthenticatedIncidentsRoute: AuthenticatedIncidentsRoute,
  AuthenticatedIntegrationRoute: AuthenticatedIntegrationRoute,
  AuthenticatedLabsRoute: AuthenticatedLabsRoute,
  AuthenticatedMonitoringRoute: AuthenticatedMonitoringRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
